### ISSUE TITLE
能否增加复制崩溃信息和生成图片发送？

### ISSUE THREAD

**Issue by sendtion** [simplepeng/SpiderMan#1]
如题，如果有复制崩溃信息和生成图片发送，就可以把崩溃日志直接发给开发人员了。对于用户来说，也可以直接反馈问题，这样比较好。

**Comment by simplepeng** [comment]
这个在日程上了，有时间就会做

**Comment by simplepeng** [comment]
@sendtion 已更新，请使用1.0.3版本
