### ISSUE TITLE
android X版本

### ISSUE THREAD

**Issue by razerdp** [simplepeng/SpiderMan#11]
请问有计划推出androidX版本吗~现在androidX上用不了

**Comment by simplepeng** [comment]
@razerdp 有考虑，但是我现在已经转到androidX并使用spiderMan没有出现什么问题
```java
implementation 'androidx.appcompat:appcompat:1.1.0'
implementation 'androidx.core:core-ktx:1.1.0'
...
def spider_man = "1.1.3"
debugApi "com.simple:spiderman:$spider_man"
releaseApi "com.simple:spiderman-no-op:$spider_man"
```
你是哪里出现了问题，贴下错误信息吧

**Comment by razerdp** [comment]
![微信截图_20191009162906](https://user-images.githubusercontent.com/11629986/66464639-f1e5f000-eab1-11e9-9245-abbe02a08c3d.png)


应该是buildconfig里面有重复字段的问题（打release包的时候出现的，我们内部release包需要展示崩溃信息，外放包则引用noop~）

**Comment by simplepeng** [comment]
@razerdp 看看build.gradle如何引用的，我试试能不能复现

**Comment by razerdp** [comment]
![微信截图_20191009165721](https://user-images.githubusercontent.com/11629986/66466797-e268a600-eab5-11e9-90cf-f062ddc9c09a.png)

其中inner依赖就是内部release使用

**Comment by simplepeng** [comment]
已更新到androidx版本
