### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by GXSZone** [simplepeng/SpiderMan#12]
作者参考下https://github.com/jenly1314/NeverCrash 这为作者的,因为异常闪退的的时候会出现黑屏(我的时间较长),是否可以参考下,不闪退的同时在显示崩溃信息,可以解决长时间黑屏的问题

**Comment by simplepeng** [comment]
@748297973 谢谢，不错的建议，之前在`releaseImpl no-op`中参考过这个项目，但是由于layout xml产生异常会造成ui卡死就删除了，之后可以在`debugImpl`中参考下，解决长时间黑屏的问题

**Comment by 401885064** [comment]
可以像leakcanary这样  完全代码无入侵方式吗？

**Comment by simplepeng** [comment]
@401885064 做不到，因为提供了一些可以自定义的东西，leakcanary这种其实也是用了一个ContentProvider做中间层而已
