### ISSUE TITLE
JCenter 弃用和服务终止

### ISSUE THREAD

**Issue by YYwishp** [simplepeng/SpiderMan#21]
JCenter 弃用和服务终止，请迁移到 mavenCentral，新项目，无法下载

**Comment by YYwishp** [comment]
似乎升级版本号，并没有解决问题

**Comment by simplepeng** [comment]
@YYwishp 用的哪个版本？最新的吗？

**Comment by YYwishp** [comment]
对，最新版本

**Comment by YYwishp** [comment]
def spider_man = "1.1.7"
def spider_man_no_op = "1.1.5"

**Comment by YYwishp** [comment]
请问一下，最近打算迁移吗？

**Comment by simplepeng** [comment]
@YYwishp 准备迁移了

**Comment by YYwishp** [comment]
thanks

**Comment by simplepeng** [comment]
@YYwishp v1.1.8迁移到jitpack了，具体的看readme

**Comment by YYwishp** [comment]
good jop
