### ISSUE TITLE
接收到崩溃，APP能监听到吗

### ISSUE THREAD

**Issue by D10NGYANG** [simplepeng/SpiderMan#22]
我想实现在崩溃后几秒后重启APP，因为我需要做一个机器人APP，一直活跃在前台监听数据，需要APP挂了也得能活过来

**Comment by simplepeng** [comment]
@D10NGYANG 可以自定义个`Thread.uncaughtException`

**Comment by D10NGYANG** [comment]
好的，谢谢您
