### ISSUE TITLE
Jitpack报错，找不到项目

### ISSUE THREAD

**Issue by lianglixin** [simplepeng/SpiderMan#26]
implementation "com.github.simplepeng.SpiderMan:spiderman:1.1.8"
上面这个可以
implementation "com.github.simplepeng.SpiderMan:spiderman:v1.1.8"
这个不行，之前可以的，请问是为什么呢

**Comment by simplepeng** [comment]
![image](https://user-images.githubusercontent.com/12198830/161944586-d977e6a2-3340-4930-ad16-7638c7dfec8f.png)
@lianglixin 我也不知道啥原因呢😂，可能jitpack抽风了吧，我试了下加v不加v都可以依赖成功。
也有可能是gradle版本不一致导致的

**Comment by EvanEvil** [comment]
404 找到这个库
https://jitpack.io/com/github/simplepeng/SpiderMan/spiderman/v1.1.8/spiderman-v1.1.8.pom

**Comment by simplepeng** [comment]
@EvanEvil 
https://jitpack.io/com/github/simplepeng/SpiderMan/spiderman/1.1.8/spiderman-1.1.8.pom
那就是不加v，我看近期直接升级到v1.1.9吧，加了点东西

**Comment by lianglixin** [comment]
可能是Jitpack抽风或者什么原因，之前加了v可以正常下载编译，后面应该是这几天不知道为什么无端端就不行了，旧的电脑甚至还有带v的缓存，新的电脑编译这个依赖第一个报404，不清楚是什么策略原因，不带v的可以，可能是近期更改了什么依赖搜索相关的内容吧。
