### ISSUE TITLE
no op 和 不加noop的版本有啥区别

### ISSUE THREAD

**Issue by liangnansheng** [simplepeng/SpiderMan#6]

**Comment by simplepeng** [comment]
@liangnansheng no-op 是给release版用的，没有捕获异常，所以不会弹出崩溃信息提示。还有就是因为大多数app release版本都会集成友盟，bugly等第三方崩溃捕获sdk，为了不和它们起冲突，原来是做了代理崩溃捕获的，但是发现很多小伙伴都不知道怎么代理捕获崩溃信息，所以才用了no-op。
