### ISSUE TITLE
优化点

### ISSUE THREAD

**Issue by hss01248** [simplepeng/SpiderMan#8]
不要拦掉crash的后续传递,可参考firebase crashytic的处理

**Comment by simplepeng** [comment]
@hss01248  没有很懂你的意思，是指的后续的log输出么？

**Comment by zhuangzeqin** [comment]
这个错误的日志；有没有保存在一个目录里；比如我可以上传给后台去

**Comment by simplepeng** [comment]
@zhuangzeqin 已经有很多三方sdk已经做了这种事，比如umeng，bugly，还有一些开源框架也做过，比如
[CrashReporter](https://github.com/MindorksOpenSource/CrashReporter)，所有我并没打算做这个功能，很抱歉
